# Generated by Django 4.1.2 on 2022-11-09 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='addresss',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='last',
            new_name='last_name',
        ),
    ]
