# Generated by Django 4.1.2 on 2022-11-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='additional_info',
            field=models.TextField(default='a'),
        ),
    ]
